<?php
/**
 * Minimal JWT (HS256) implementation — no Composer dependency.
 */
class Jwt {

    public static function secret(): string {
        $env = getenv('JWT_SECRET');
        if ($env && strlen($env) >= 32) return $env;

        // Per-install persistent secret. Stored under the runtime/ folder,
        // which we fail-closed protect with an .htaccess deny rule and an
        // index.php that returns 403, so HTTP cannot read it even if the
        // hosting environment serves storage/ statically.
        $dir  = dirname(__DIR__, 3) . '/storage/runtime';
        $path = $dir . '/jwt_secret';

        if (!self::ensureProtectedDir($dir)) {
            // We could not write the deny rules — fail closed with an
            // in-memory ephemeral secret. Sessions won't survive a process
            // restart, but no secret can possibly leak via HTTP.
            static $mem = null;
            if ($mem === null) $mem = bin2hex(random_bytes(32));
            error_log('[Jwt] runtime/ directory could not be protected; using ephemeral in-memory secret.');
            return $mem;
        }

        if (is_readable($path)) {
            $s = trim((string)@file_get_contents($path));
            if (strlen($s) >= 32) return $s;
        }

        $new = bin2hex(random_bytes(32));
        if (@file_put_contents($path, $new, LOCK_EX) === false) {
            static $mem2 = null;
            if ($mem2 === null) $mem2 = bin2hex(random_bytes(32));
            error_log('[Jwt] Could not persist secret to '.$path.' — using ephemeral in-memory secret.');
            return $mem2;
        }
        @chmod($path, 0600);
        return $new;
    }

    /**
     * Guarantee that the runtime directory exists and is HTTP-deny protected.
     * Writes .htaccess (Apache) and a 403 index.php (universal fallback for
     * servers that don't honor .htaccess). Returns false if any protection
     * step fails — callers should then refuse to persist secrets there.
     */
    private static function ensureProtectedDir(string $dir): bool {
        if (!is_dir($dir) && !@mkdir($dir, 0750, true) && !is_dir($dir)) {
            return false;
        }
        @chmod($dir, 0750);

        $htaccess = $dir . '/.htaccess';
        if (!is_file($htaccess)) {
            $rule = "# Auto-generated by Jwt::ensureProtectedDir — do not remove.\n"
                  . "<IfModule mod_authz_core.c>\n    Require all denied\n</IfModule>\n"
                  . "<IfModule !mod_authz_core.c>\n    Order allow,deny\n    Deny from all\n</IfModule>\n";
            if (@file_put_contents($htaccess, $rule, LOCK_EX) === false) return false;
            @chmod($htaccess, 0640);
        }

        $index = $dir . '/index.php';
        if (!is_file($index)) {
            $body = "<?php http_response_code(403); exit('Forbidden');\n";
            if (@file_put_contents($index, $body, LOCK_EX) === false) return false;
            @chmod($index, 0640);
        }
        return true;
    }

    private static function b64u_encode(string $bin): string {
        return rtrim(strtr(base64_encode($bin), '+/', '-_'), '=');
    }

    private static function b64u_decode(string $s): string {
        $pad = strlen($s) % 4;
        if ($pad) $s .= str_repeat('=', 4 - $pad);
        return base64_decode(strtr($s, '-_', '+/')) ?: '';
    }

    /**
     * @param array  $payload  ['sub'=>id,'type'=>'user|client',...]
     * @param int    $ttlSec   lifetime in seconds (default 1h)
     */
    public static function sign(array $payload, int $ttlSec = 3600): string {
        $now = time();
        $payload = array_merge([
            'iat' => $now,
            'exp' => $now + $ttlSec,
        ], $payload);

        $header  = ['alg' => 'HS256', 'typ' => 'JWT'];
        $h64 = self::b64u_encode(json_encode($header, JSON_UNESCAPED_SLASHES));
        $p64 = self::b64u_encode(json_encode($payload, JSON_UNESCAPED_SLASHES));
        $sig = hash_hmac('sha256', "$h64.$p64", self::secret(), true);
        $s64 = self::b64u_encode($sig);
        return "$h64.$p64.$s64";
    }

    /** @return array|null Decoded payload or null on failure. */
    public static function verify(string $token): ?array {
        $parts = explode('.', $token);
        if (count($parts) !== 3) return null;
        [$h64, $p64, $s64] = $parts;
        $expected = self::b64u_encode(hash_hmac('sha256', "$h64.$p64", self::secret(), true));
        if (!hash_equals($expected, $s64)) return null;
        $payload = json_decode(self::b64u_decode($p64), true);
        if (!is_array($payload)) return null;
        if (isset($payload['exp']) && time() >= intval($payload['exp'])) return null;
        return $payload;
    }

    public static function randomToken(int $bytes = 48): string {
        return rtrim(strtr(base64_encode(random_bytes($bytes)), '+/', '-_'), '=');
    }

    public static function hashRefresh(string $token): string {
        return hash('sha256', $token);
    }
}
