// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile-home-screen/CurrentIcon.tsx": () => import("../components/mockups/mobile-home-screen/CurrentIcon.tsx")
};
